micronaut:
  application:
    name: eventos-da-rep-api
  server:
    port: ${PORT:8080}

datasources:
  default:
    url: ${DATABASE_URL_2}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    schema-generate: CREATE
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3

server:
  port: ${PORT:8080}