micronaut:
  application:
    name: eventos-da-rep-api
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - https://eventos-da-rep-admin.herokuapp.com
  server:
    port: ${PORT:8080}

datasources:
  default:
    url: ${DATABASE_URL_2:jdbc:postgresql://localhost:5432/eventos_da_rep_db}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER:eventos_da_rep_admin}
    password: ${DATABASE_PASSWORD:1234}
    schema-generate: CREATE
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3

server:
  port: ${PORT:8080}

rabbitmq:
  username: ${RABBITMQ_USERNAME:admin}
  password: ${RABBITMQ_PASSWORD:1234}
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}