micronaut:
  application:
    name: eventos-da-rep-api

datasources:
  default:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    schema-generate: CREATE
    dialect: POSTGRES

netty:
  default:
    allocator:
      max-order: 3