micronaut:
  application:
    name: eventos-da-rep-api
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://admin:1234@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/eventosdarep?authSource=admin


