name: ci
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      #      - name: Run Format code lint
      #        run: ./gradlew ktlintFormat
      #
      #      - name: Run Lint
      #        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Creating artifact
        run: mkdir production && cp build/libs/eventos-da-rep-api-0.1-all.jar production

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: GitHub_Actions-prd
          path: production
